apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-internal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

    {{- if .Values.ingress.corsAllowOrigin }}
    # cors
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.ingress.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-methods: "DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT"
    nginx.ingress.kubernetes.io/cors-expose-headers: "Date, Location, Request-Context, Set-Cookie"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Disposition, Content-Type, Referer, X-Locale, X-Requested-With"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-max-age: "60"
    {{- end }}
spec:
  ingressClassName: internal
  rules:
  - http:
      paths:
      
      - backend:
          service:
            name: api-gateway
            port:
              number: 80
        path: {{ .Values.ingress.path }}(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - '{{ .Values.ingress.hosts }}'
